#!/usr/bin/env bash


#Sets the playlist to play:
$DEFAULT 
# $MOVIES
# $C64

##Turns off cursor blink on display
setterm -cursor off > /dev/tty0

##Clear the term before firing up omxplayer
clear > /dev/tty0



if [ -v $DEFAULT ]
then
  echo "Default Playlist"
  ## Play some videos
  while true; do
  clear > /dev/tty0
  omxplayer --fps 24 --no-osd -z --aspect-mode stretch /home/pi/PiBadge24/videos/default.mp4
  clear > /dev/tty0
  omxplayer --fps 24 --no-osd -z --aspect-mode stretch /home/pi/PiBadge24/videos/DC_Movie.mp4
  clear > /dev/tty0
  omxplayer --fps 24 --no-osd -z --aspect-mode stretch /home/pi/PiBadge24/videos/DC64.mp4
  clear > /dev/tty0
  done
  # setterm -cursor on > /dev/tty0

elif [ -v $MOVIES ]
then
  echo "Movies"
  omxplayer --loop --fps 24 --no-osd -z --aspect-mode stretch /home/pi/PiBadge24/videos/DC_Movie.mp4 &

elif [ -v $C64 ]
then
  echo "C64"
  omxplayer --loop --fps 24 --no-osd -z --aspect-mode stretch /home/pi/PiBadge24/videos/DC64.mp4 &
 
fi

